<a href="https://colab.research.google.com/github/wlodarma/udemy-py/blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [9]:
x = np.array([1, 3])
x

array([1, 3])

In [10]:
print(x)

[1 3]


In [11]:
type(x)

numpy.ndarray

In [12]:
x.ndim

1

In [13]:
x.shape

(2,)

In [15]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [18]:
x = np.array([1.3, 2.3, 3.3])
print(x)

[1.3 2.3 3.3]


In [19]:
x.shape

(3,)

In [20]:
x.dtype

dtype('float64')

In [22]:
x = np.array([[1,2], [-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x.dtype

dtype('int64')

In [31]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]],
     
     [[3,2,1],
     [4,2,1]]])

print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 2 1]]]


In [33]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.arange(start=100, stop=9, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [41]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
a = np.array([3,1,4,2])
b = np.array([3, -1, 3, 2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


In [44]:
a+b

array([6, 0, 7, 4])

In [45]:
a-b

array([0, 2, 1, 0])

In [46]:
a*b

array([ 9, -1, 12,  4])

In [47]:
a/b

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [48]:
a+3

array([6, 4, 7, 5])

In [49]:
a-2

array([ 1, -1,  2,  0])

In [50]:
a*2

array([6, 2, 8, 4])

In [52]:
a+3*b

array([12, -2, 13,  8])

In [53]:
np.add(a,b)

array([6, 0, 7, 4])

In [55]:
np.subtract(a,b)

array([0, 2, 1, 0])

In [56]:
np.multiply(a,b)

array([ 9, -1, 12,  4])

In [57]:
np.divide(a,b)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [60]:
x = np.array([[1,3], [-2, 0]])
y=np.array([[6,0], [-1,2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [61]:
x*y

array([[6, 0],
       [2, 0]])

In [62]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [63]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [64]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [65]:
x@y

array([[  3,   6],
       [-12,   0]])

In [66]:
np.random.seed(0)

In [67]:
np.random.randn()

1.764052345967664

In [68]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [69]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [70]:
np.random.rand()

0.1965823616800535

In [71]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [72]:
np.random.rand(10,4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [74]:
np.random.randint(10)

8

In [75]:
np.random.randint(low=10, high=101)

26

In [77]:
np.random.choice([4,2,1,4])

2

In [78]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.random.shuffle(data)

In [80]:
data

array([7, 2, 8, 6, 3, 9, 1, 4, 0, 5])

In [81]:
np.exp(1)

2.718281828459045

In [82]:
np.exp(2)

7.38905609893065

In [83]:
np.sqrt(4)

2.0

In [84]:
np.all([2,3,1])

True

In [87]:
np.any([0,0,0])

False

In [89]:
a=np.random.rand(5)
a

array([0.287991  , 0.38346223, 0.74916984, 0.87845219, 0.10286336])

In [90]:
np.argmax(a)

3

In [91]:
a[np.argmax(a)]

0.878452190276042

In [92]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
a[2:7]

array([2, 3, 4, 5, 6])

In [99]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [102]:
a[:,-1]

array([ 4,  9, 14, 19])

In [103]:
a[1, 2]

7

In [104]:
a[1,2]=14
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [106]:
a>10

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [107]:
a[a>10]

array([14, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [109]:
np.bitwise_and(a>4, a<10)

array([[False, False, False, False, False],
       [ True,  True, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [110]:
a[np.bitwise_and(a>4, a<10)]

array([5, 6, 8, 9])